version: '3.8'
services:
  jenkins:
    network_mode: host  # Добавьте эту строку
    ports:
      - "8080:8080"
      - "2443:2443"  # Порт для OpenBMC
    volumes:
      - ./:/var/jenkins_home/workspace  # Монтируем текущую папку
      - /var/run/docker.sock:/var/run/docker.sock
